apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation #,HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: notification
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Application: $ARGOCD_APP_NAME"
              echo "Namespace: $ARGOCD_APP_NAMESPACE"
              echo "Project: $ARGOCD_APP_PROJECT_NAME"
              echo "Revision: $ARGOCD_APP_REVISION"
              echo "Source Repo: $ARGOCD_APP_SOURCE_REPO_URL"
              echo "Source Path: $ARGOCD_APP_SOURCE_PATH"
          env:
            - name: ARGOCD_APP_NAME
              value: "$(ARGOCD_APP_NAME)"
            - name: ARGOCD_APP_NAMESPACE
              value: "$(ARGOCD_APP_NAMESPACE)"
            - name: ARGOCD_APP_PROJECT_NAME
              value: "$(ARGOCD_APP_PROJECT_NAME)"
            - name: ARGOCD_APP_REVISION
              value: "$(ARGOCD_APP_REVISION)"
            - name: ARGOCD_APP_SOURCE_REPO_URL
              value: "$(ARGOCD_APP_SOURCE_REPO_URL)"
            - name: ARGOCD_APP_SOURCE_PATH
              value: "$(ARGOCD_APP_SOURCE_PATH)"
      restartPolicy: Never
