apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2 # Update the replica count to 2
  selector:
    matchLabels:
      app: web
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
